spring.application.name=jobautomate
server.port=${PORT:8080}

spring.datasource.url=jdbc:h2:mem:jobassistant;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173,https://jafrontend-bi2n.onrender.com
app.scheduler.cron=0 0 3 * * *

app.jobs.provider=adzuna
app.jobs.seed-fallback-enabled=true
app.jobs.adzuna.base-url=https://api.adzuna.com/v1/api/jobs
app.jobs.adzuna.app-id=c65a7727
app.jobs.adzuna.app-key=c78a32ee61bde3480cb95796b7bb1480
app.jobs.adzuna.results-per-page=20
app.jobs.adzuna.pages-per-country=1
app.jobs.adzuna.max-days-old=7
app.jobs.adzuna.search-countries=in

app.jobs.jsearch.base-url=https://jsearch.p.rapidapi.com
app.jobs.jsearch.rapid-api-key=52f88e7ecemsh88b1a5e78accc11p1af58cjsna18472943ac8
app.jobs.jsearch.rapid-api-host=jsearch.p.rapidapi.com
app.jobs.jsearch.page=1
app.jobs.jsearch.num-pages=1
app.jobs.jsearch.country=in
app.jobs.jsearch.timeout-ms=10000

app.jobs.jooble.base-url=https://jooble.org/api
app.jobs.jooble.api-key=118c1eac-c640-4ab7-9510-36e5bf23d8c7
app.jobs.jooble.page=1
app.jobs.jooble.results-per-page=20
app.jobs.jooble.default-location=India
app.jobs.jooble.timeout-ms=10000

app.jobs.aggregation.similarity-threshold=0.5
app.jobs.aggregation.top-limit=60
app.jobs.aggregation.provider-concurrency=3
app.jobs.aggregation.adzuna-share=0.5
app.jobs.aggregation.jooble-share=0.3
app.jobs.aggregation.jsearch-share=0.2

hf.embedding.url=https://api-inference.huggingface.co/hf-inference/models/BAAI/bge-small-en-v1.5
hf.api.key=${HF_API_KEY}
hf.embedding.batch-size=10

spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD}
